version: '3'
services:
    influxdb:
        image: 'influxdb:2.7'
        ports:
            - 8086:8086
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
            - DOCKER_INFLUXDB_INIT_ORG=garie
            - DOCKER_INFLUXDB_INIT_BUCKET=default
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev-token

    webbkoll-backend:
        image: eeacms/webbkoll-backend:299372-upgrade

    webbkoll:
        image: eeacms/webbkoll:299372-upgrade
        environment:
            - BACKEND_HOST=webbkoll-backend
            - BACKEND_PORT=8100
        ports:
            - 4000:4000
        depends_on:
            - webbkoll-backend
        links:
            - webbkoll-backend:webbkoll-backend

    garie-plugin:
        build: .
        privileged: true
        volumes:
            - ./src:/usr/src/garie-plugin/src:z
            - ./config.json:/usr/src/garie-plugin/config.json:z
            - /var/run/docker.sock:/run/docker.sock
            - /usr/bin/docker:/bin/docker
        ports:
            - 3000:3000
        environment:
            - HOST=influxdb
            - BACKEND_HOST=webbkoll-backend
            - BACKEND_PORT=8100
            - WEBBKOLL_HOST=webbkoll
            - WEBBKOLL_PORT=4000
            - INFLUX_TOKEN=dev-token
            - INFLUX_ORG=garie
        links:
            - influxdb
            - webbkoll-backend:webbkoll-backend
            - webbkoll:webbkoll
        depends_on:
            - influxdb
            - webbkoll
        command: bash -c "tail -f /dev/null"
